if not "%OS%"=="Windows_NT" if "%COMSPEC%"=="C:\COMMAND.COM"  set SMS_LOCAL_DIR=C:\WINDOWS
PATH=%PATH%;C:\PROGRA~1\ULTRAEDT;C:\WINDOWS;C:\WINDOWS\SYSTEM;C:\WINDOWS\SYSTEM\WBEM;C:\PROGRA~1\MICROS~7\80\TOOLS\BINN
Rem TShoot: SET PATH=%PATH%;C:\PROGRA~1\BORLAND\DELPHI4\BIN;C:\PROGRA~1\SQLLIB\BIN;C:\PROGRA~1\SQLLIB\FUNCTION;C:\PROGRA~1\SQLLIB\SAMPLES\REPL;C:\PROGRA~1\SQLLIB\HELP
SET PATH=%PATH%;C:\PROGRA~1\SQLLIB\BIN;C:\PROGRA~1\SQLLIB\FUNCTION;C:\PROGRA~1\SQLLIB\SAMPLES\REPL;C:\PROGRA~1\SQLLIB\HELP
IF EXIST C:\PROGRA~1\IBM\IMNNQ\IMNENV.BAT CALL C:\PROGRA~1\IBM\IMNNQ\IMNENV.BAT
set INCLUDE=C:\PROGRA~1\SQLLIB\INCLUDE;C:\PROGRA~1\SQLLIB\LIB
set LIB=C:\PROGRA~1\SQLLIB\LIB
set DB2INSTANCE=DB2
set DB2TEMPDIR=C:\PROGRA~1\SQLLIB
set CLASSPATH=.;C:\PROGRA~1\SQLLIB\java\db2java.zip;C:\PROGRA~1\SQLLIB\java\runtime.zip;C:\PROGRA~1\SQLLIB\java\sqlj.zip;C:\PROGRA~1\SQLLIB\bin
set VWS_LOGGING=C:\PROGRA~1\SQLLIB\LOGGING
set VWSPATH=C:\PROGRA~1\SQLLIB
set VWS_FOLDER=IBM DB2
set ICM_FOLDER=Information Catalog Manager
set MDIS_PROFILE=C:\PROGRA~1\SQLLIB\METADATA\PROFILES
set LC_ALL=EN_US

PATH=%PATH%;"C:\Program Files\Mts"
